In [1]:
import pandas as pd
import numpy as np

In [2]:
 df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

In [3]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [ ]:
 """
 Numpy
 
 NumPy is a powerful library in Python 
 for numerical operations. 
 It provides support for large, 
 multi-dimensional arrays and matrices, 
 along with a collection of mathematical functions 
 to operate on these elements.
 """

ARRAY

In [4]:
l = ["kush", 1, 2, 3, 4]

In [5]:
type(l)

list

In [6]:
np.array(l)

array(['kush', '1', '2', '3', '4'], dtype='<U11')

In [ ]:
"""
An array is a data structure that 
stores elements of the same data type 
in contiguous memory locations. 
The elements in an array can be accessed 
using an index or a key. 
Arrays are widely used in programming 
and are essential for various algorithms 
and data manipulation tasks.


In the context of programming languages 
like Python and NumPy (as mentioned earlier), 
arrays are often used to represent collections of values, 
particularly when those values need to be accessed 
or manipulated in a systematic way.

For example, in Python, 
a simple list can be considered an array:
"""
my_list = [1, 2, 3, 4, 5]

"""
In this list, each element is accessed by an index 
(position in the list). 
In Python, indexing starts at 0, 
so my_list[0] would give you the first element, 
my_list[1] would give you the second element, and so on.


NumPy arrays, as mentioned earlier, 
provide a more powerful and efficient way to work with arrays 
for numerical operations in Python. 
They are homogeneous, 
meaning all elements must be of the same data type, 
and they support operations that are performed element-wise.

"""

In [7]:
type(np.array(l))

# Here the 'ndarray' type means
# "n dimentional array"

numpy.ndarray

In [8]:
a1 = np.array([3,4,5,6,4.0])
a1

# As we can observe here that 
# Because of 1 floting point element
# The entire array was converted as 
# a array with all flot elements

# So its kind of typecasting on all the elements

array([3., 4., 5., 6., 4.])

In [9]:
# Simillarly
a = np.array([[1,2], [3,4]])
a

# We can observe here that it automatically
# Set the 2 lists vertically 
# Just like a matrix

array([[1, 2],
       [3, 4]])

In [10]:
# Requirement:
# we want to pull 4 from the above 'a' variable

a[1][1]

# Works just like extracting data from a list

4

In [11]:
a1

array([3., 4., 5., 6., 4.])

In [12]:
a1[1]

4.0

In [69]:
# Slicing options works the same as the list

a1[1:3]

array([4., 5.])

In [ ]:
"""
np.array() syntax and docstring

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.
"""


"""
Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    __array__ method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array.  If not given, then the type will
    be determined as the minimum type required to hold the objects in the
    sequence.
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if __array__ returns a copy, if obj is a nested sequence,
    or if a copy is needed to satisfy any of the other requirements
    (`dtype`, `order`, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly created array will be in C order (row major) unless 'F' is
    specified, in which case it will be in Fortran order (column major).
    If object is an array the following holds.

    ===== ========= ===================================================
    order  no copy                     copy=True
    ===== ========= ===================================================
    'K'   unchanged F & C order preserved, otherwise most similar order
    'A'   unchanged F order if input is F and not C, otherwise C order
    'C'   C order   C order
    'F'   F order   F order
    ===== ========= ===================================================

    When ``copy=False`` and a copy is made for other reasons, the result is
    the same as if ``copy=True``, with some exceptions for 'A', see the
    Notes section. The default order is 'K'.
subok : bool, optional
    If True, then sub-classes will be passed-through, otherwise
    the returned array will be forced to be a base-class array (default).
ndmin : int, optional
    Specifies the minimum number of dimensions that the resulting
    array should have.  Ones will be prepended to the shape as
    needed to meet this requirement.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0
"""


"""
Returns
-------
out : ndarray
    An array object satisfying the specified requirements.
"""


"""
See Also
--------
empty_like : Return an empty array with shape and type of input.
ones_like : Return an array of ones with shape and type of input.
zeros_like : Return an array of zeros with shape and type of input.
full_like : Return a new array with shape of input filled with value.
empty : Return a new uninitialized array.
ones : Return a new array setting values to one.
zeros : Return a new array setting values to zero.
full : Return a new array of given shape filled with value.

"""


"""
Notes
-----
When order is 'A' and `object` is an array in neither 'C' nor 'F' order,
and a copy is forced by a change in dtype, then the order of the result is
not necessarily 'C' as expected. This is likely a bug.

"""

In [13]:
# NOTE:
# There is a parameter "ndmin"
# Which indicated dimention for that array
# Examples below
np.array([1,2,3,4], ndmin= 0)

# Nothing changes

array([1, 2, 3, 4])

In [14]:
np.array([1,2,3,4], ndmin= 1)

# Again Nothing changes

array([1, 2, 3, 4])

In [15]:
# But as soon as we go further to 'ndmin' as 2
# We can spot changes

np.array([1,2,3,4], ndmin= 2)

# As we can observe that the number of '[]' increased

array([[1, 2, 3, 4]])

In [16]:
np.array([1,2,3,4], ndmin= 3)

# Now the number of '[]' increased to 3

array([[[1, 2, 3, 4]]])

In [17]:
a2 = np.array([1,2,3,4], ndmin= 4)
a2
# Now the number of '[]' increased to 4

array([[[[1, 2, 3, 4]]]])

In [18]:
# SO basically the dimention mans that 
# how nested the array is.

# If we have arrays nested inside an array 
# Then the dimention of that array increases.

In [19]:
# Now if we want to extract the value. 
a2[0]

# a2[0] will only go 1 dimention inside

array([[[1, 2, 3, 4]]])

In [20]:
# to get 1 from the array 'a2'

a2[0][0][0][0]

# So here we have drilled down to the 
# inner most nested array to fetch 1

1

In [21]:
# We can also say that array
a

# has 2 dimentions

array([[1, 2],
       [3, 4]])

In [22]:
# Simillarly we also have 
# "np.asarray()" and 'np.asanyarray()'

np.asarray([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [23]:
np.asanyarray([1, 2, 3, 4, 5, 6])

# Both gives same results

array([1, 2, 3, 4, 5, 6])

MATRIX Data type

In [24]:
np.mat([1, 2, 3, 4, 5])

# As we can observe here that 
# Matrixes are by default '2D elements'

matrix([[1, 2, 3, 4, 5]])

In [ ]:
"""
In NumPy, a matrix is a specialized 2-dimensional array. 
NumPy provides the numpy.matrix class, 

which is similar to the numpy.ndarray class 
but with additional matrix-specific functionality. 

You can create matrices using the matrix function 
or by directly using the numpy.matrix class.
"""

More DATA Extraction

In [25]:
np.fromfunction(lambda i, j: i == j, (3,3))

# In this example 'lambda i, j: i == j' is teh function
# And '(3,3)' is the matrix/arrays 
# rows and column values. 

# Here J is column and i is rows. 
# And the function is trying to check the index of i and j
# And if both the index is equal
# It will pass true. else false

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [26]:
np.fromfunction(lambda i, j: i*j, (4,4))

# This example explains the above explanation properly
# Here we can see that its multiplying the i and j 
# indexes and giving the results accordingly.

# NOTE:
# numpy module will always return 
# Floting point numbers by default in case of 
# Multiplication, Division and cast operations
# unless specified. 

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [27]:
# In case you want to have only int type 
# Then you have to use parameter 'dtype'

np.fromfunction(lambda i, j: i*j, (4,4), dtype = int)

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])

In [28]:
# NOTE:
# By default it will give the values ad array only
# In case you want it to be matrix
# You have to convert them into matrix

np.mat(np.fromfunction(lambda i, j: i*j, (4,4), dtype= int))

matrix([[0, 0, 0, 0],
        [0, 1, 2, 3],
        [0, 2, 4, 6],
        [0, 3, 6, 9]])

FromFunction, Shape and Size functions

In [29]:
# Now lets try somting different
# We can try to create a 3D matrix 
# Which in itself in possible

np.mat(np.fromfunction(lambda i, j, z: i*j*z, (3,3,3)))

ValueError: shape too large to be a matrix.

In [30]:
# But we can create an array with 3 dimentions

np.fromfunction(lambda i, j, z: i*j*z, (3,3,2), dtype= int)

# IMPORTANT
# In the above example we have mentioned "(3,3,2)"
# in which 
# 1st 3 means: we need 3 matrixes/arrays which is 'i'
# And the later (3,2) means: 
# we need array with those cross-section
# 3 rows and 3 columns which is '(j,z)'

# In a nutshell it means we need 3 matrixes/arrays
# of (3,2) cross-section

# If we explin the values in the matrix
# 'i' for the 1st matrix is '0'
# that is why all the values of that array have 0 value

# 'i' for the 2nd matrix/array is '1' 
# That is why you have 1 and 2 value at the end 

# simillarly 'i' for the last matrix/array is '2'
# that's why we have 2 and 4 at the end
# its the double of the 2nd matrix

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]]])

In [31]:
# Now from the above understanding. 
# If we want to create a 4D array

np.fromfunction(lambda i, j, z, p: i*j*z*p, (4,3,3,2), dtype= int)

# This gives us an 4 dimention array

array([[[[ 0,  0],
         [ 0,  0],
         [ 0,  0]],

        [[ 0,  0],
         [ 0,  0],
         [ 0,  0]],

        [[ 0,  0],
         [ 0,  0],
         [ 0,  0]]],


       [[[ 0,  0],
         [ 0,  0],
         [ 0,  0]],

        [[ 0,  0],
         [ 0,  1],
         [ 0,  2]],

        [[ 0,  0],
         [ 0,  2],
         [ 0,  4]]],


       [[[ 0,  0],
         [ 0,  0],
         [ 0,  0]],

        [[ 0,  0],
         [ 0,  2],
         [ 0,  4]],

        [[ 0,  0],
         [ 0,  4],
         [ 0,  8]]],


       [[[ 0,  0],
         [ 0,  0],
         [ 0,  0]],

        [[ 0,  0],
         [ 0,  3],
         [ 0,  6]],

        [[ 0,  0],
         [ 0,  6],
         [ 0, 12]]]])

In [33]:
# To know the dimention of the array
# We can use "ndim" function

a3 = np.fromfunction(lambda i, j, z: i*j*z, (4,3,2), dtype= int)
a3.ndim

3

In [34]:
# Here the "size" function we tell us 
# How many elements are there in the array
a3.size

# Which is in this situation 4*3*2 = 24

24

In [35]:
a3.shape

# "shape" function will give you the dimentions 
# in details as shown in the output

(4, 3, 2)

In [36]:
a3.dtype

# Here dtype "int32" means 
# It has a capacity of 32bits to store int values

dtype('int32')

DataFrame with numpy

In [37]:
# TO convert an array into a dataframe
# we can use the 'dataframe' function 
# form the pandas module

pd.DataFrame(a3)

# To convert an array into a dataframe
# The array must be an 2D array
# Otherwise it gives an error

ValueError: Must pass 2-d input. shape=(4, 3, 2)

In [38]:
# To rectify this 
# first think is to pass an 2D array

a4 = np.fromfunction(lambda i, j: i*j, (4,3), dtype= int)
pd.DataFrame(a4)

# It works without an error
# There are other ways to convery a 3D or more dimention
# array to dataframe. That we will learn later

0  1  2
0  0  0  0
1  0  1  2
2  0  2  4
3  0  3  6

In [39]:
# Its very convineant 
# to create large dataframe with this

a4 = np.fromfunction(lambda i, j: i*j, (400,300), dtype= int)
pd.DataFrame(a4)

0    1    2     3     4     5     6     7     8     9    ...     290  \
0      0    0    0     0     0     0     0     0     0     0  ...       0   
1      0    1    2     3     4     5     6     7     8     9  ...     290   
2      0    2    4     6     8    10    12    14    16    18  ...     580   
3      0    3    6     9    12    15    18    21    24    27  ...     870   
4      0    4    8    12    16    20    24    28    32    36  ...    1160   
..   ...  ...  ...   ...   ...   ...   ...   ...   ...   ...  ...     ...   
395    0  395  790  1185  1580  1975  2370  2765  3160  3555  ...  114550   
396    0  396  792  1188  1584  1980  2376  2772  3168  3564  ...  114840   
397    0  397  794  1191  1588  1985  2382  2779  3176  3573  ...  115130   
398    0  398  796  1194  1592  1990  2388  2786  3184  3582  ...  115420   
399    0  399  798  1197  1596  1995  2394  2793  3192  3591  ...  115710   

        291     292     293     294     295     296     297     298     299  
0         0       0       0       0       0       0       0       0       0  
1       291     292     293     294     295     296     297     298     299  
2       582     584     586     588     590     592     594     596     598  
3       873     876     879     882     885     888     891     894     897  
4      1164    1168    1172    1176    1180    1184    1188    1192    1196  
..      ...     ...     ...     ...     ...     ...     ...     ...     ...  
395  114945  115340  115735  116130  116525  116920  117315  117710  118105  
396  115236  115632  116028  116424  116820  117216  117612  118008  118404  
397  115527  115924  116321  116718  117115  117512  117909  118306  118703  
398  115818  116216  116614  117012  117410  117808  118206  118604  119002  
399  116109  116508  116907  117306  117705  118104  118503  118902  119301  

[400 rows x 300 columns]

Random Function in Numpy

In [40]:
# 'rand' function in the np.random module
# will create a random array
# from the given dimention

np.random.rand(100,4)

# Input here should always be a dimention
# It creates randon float valus btw 0 and 1

array([[0.83949424, 0.93299658, 0.35261306, 0.56743967],
       [0.34363995, 0.40924488, 0.45480493, 0.11271153],
       [0.41280134, 0.19849535, 0.02933007, 0.46477811],
       [0.21745494, 0.26711131, 0.91499793, 0.83831783],
       [0.38267693, 0.39859483, 0.25419258, 0.43860829],
       [0.98664309, 0.71819627, 0.79074384, 0.1893419 ],
       [0.5763398 , 0.95599649, 0.11838882, 0.06342606],
       [0.55390509, 0.38782017, 0.04300797, 0.79838592],
       [0.58526229, 0.83625515, 0.80041746, 0.05022619],
       [0.24623947, 0.06593697, 0.29164937, 0.60036936],
       [0.72507195, 0.59432133, 0.48034269, 0.64301017],
       [0.08531399, 0.8952282 , 0.89694896, 0.96541997],
       [0.71628718, 0.1873299 , 0.2802168 , 0.10035538],
       [0.231509  , 0.08826838, 0.6444394 , 0.83597093],
       [0.22652679, 0.20216428, 0.4554476 , 0.73987198],
       [0.69298967, 0.43981688, 0.6742296 , 0.61717638],
       [0.46002464, 0.21983798, 0.60640009, 0.42680272],
       [0.8523368 , 0.23586033,

In [ ]:
"""
rand Systax and Dockstring

Docstring:
rand(d0, d1, ..., dn)

Random values in a given shape.

.. note::
    This is a convenience function for users porting code from Matlab,
    and wraps `random_sample`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.

Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned array, must be non-negative.
    If no argument is given a single Python float is returned.

Returns
-------
out : ndarray, shape ``(d0, d1, ..., dn)``
    Random values.
"""

In [41]:
# 'randint' function will generate a random 
# int value btw the range given 

np.random.randint(4,50)

11

In [ ]:
"""
Docstring:
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the `~numpy.random.Generator.randint`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-like, must contain integer values
size : int or tuple of ints, optional
    Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
    ``m * n * k`` samples are drawn.  Default is None, in which case a
    single value is returned.
dtype : dtype, optional
    Desired dtype of the result. Byteorder must be native.
    The default value is int.

    .. versionadded:: 1.11.0

Returns
-------
out : int or ndarray of ints
    `size`-shaped array of random integers from the appropriate
    distribution, or a single such random int if `size` not provided.
"""

In [42]:
# 'randn' function will 

np.random.randn(4,5)

# It given a random array with 'normal distribution'
# In case we find the average of these numbers it will be 0
# and standrad distribution of these numbers will be 1

# More details below

array([[ 0.23661481, -0.5142779 , -0.95902521,  0.54919565,  0.13336619],
       [-0.20017484,  0.40025882, -0.27292579, -0.69917161,  0.57976419],
       [-1.62448353, -0.01270054, -0.83364023,  1.50725097, -0.83391162],
       [-1.64711802, -1.23983565,  0.84096193, -0.64125872, -1.00218837]])

In [ ]:
"""
Docstring:
randn(d0, d1, ..., dn)

Return a sample (or samples) from the "standard normal" distribution.

.. note::
    This is a convenience function for users porting code from Matlab,
    and wraps `standard_normal`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.

.. note::
    New code should use the
    `~numpy.random.Generator.standard_normal`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

If positive int_like arguments are provided, `randn` generates an array
of shape ``(d0, d1, ..., dn)``, filled
with random floats sampled from a univariate "normal" (Gaussian)
distribution of mean 0 and variance 1. A single float randomly sampled
from the distribution is returned if no argument is provided.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned array, must be non-negative.
    If no argument is given a single Python float is returned.

Returns
-------
Z : ndarray or float
    A ``(d0, d1, ..., dn)``-shaped array of floating-point samples from
    the standard normal distribution, or a single such float if
    no parameters were supplied.
"""

In [43]:
# Now if we want to create a df
pd.DataFrame(np.random.randn(4,5))

0         1         2         3         4
0 -1.456623  0.377527 -0.405312 -0.544471 -0.114527
1  0.359268 -0.796624 -1.767937  1.065213 -1.485569
2 -1.479832 -1.628115  1.189978 -1.137285 -2.777397
3  0.475536  1.219215  1.795479  0.139409 -1.132073

Reshaping the array

In [47]:
a3.ndim

3

In [48]:
a3.shape

(4, 3, 2)

In [54]:
a3.size

24

In [49]:
# To reshape a array 
# we can use the 'reshape' function
# Where we will provide the new dimentions/shape inside '()'

a3.reshape(5,5)

# This reshape operation will not work 
# Because the new dimentions/shape are 5 and 5 
# Which are not related to earlier dimentions/shape

ValueError: cannot reshape array of size 24 into shape (5,5)

In [50]:
# To fix this 
# we can try changing the dimention/shape as

a3.reshape(12,2)

# So we multiplied 4 and 3 
# and set the new row value as 12

# This only works if the new shape mentioned
# is in factor of 24 (size of the array)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 2],
       [0, 0],
       [0, 2],
       [0, 4],
       [0, 0],
       [0, 3],
       [0, 6]])

In [52]:
# We can also set teh dimentions/shape like below

a3.reshape(6,4)

# Here we multiplied 3 and 2 
# and kept the 4 as columns

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 2],
       [0, 0, 0, 2],
       [0, 4, 0, 0],
       [0, 3, 0, 6]])

In [53]:
# And

a3.reshape(8,3)

# This will work with combinations of
# factors of 24 (which is the size of the array) 

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [1, 0, 2],
       [0, 0, 0],
       [2, 0, 4],
       [0, 0, 0],
       [3, 0, 6]])

In [55]:
# And

a3.reshape(1,24)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 2, 0, 4, 0, 0, 0, 3,
        0, 6]])

In [56]:
# After reshaping we can convert it into a df
pd.DataFrame(a3.reshape(8,3))

0  1  2
0  0  0  0
1  0  0  0
2  0  0  0
3  1  0  2
4  0  0  0
5  2  0  4
6  0  0  0
7  3  0  6

In [58]:
# Simmilarly 
# reshaping can not only decrease the dimention
# It can also increase the dimention
# Provided the shape is still in the 
# Factors of the size of teh array

a3.reshape(4,2,1,3,1,1)

# Converted it into a 6D array

array([[[[[[0]],

          [[0]],

          [[0]]]],



        [[[[0]],

          [[0]],

          [[0]]]]],




       [[[[[0]],

          [[0]],

          [[0]]]],



        [[[[1]],

          [[0]],

          [[2]]]]],




       [[[[[0]],

          [[0]],

          [[0]]]],



        [[[[2]],

          [[0]],

          [[4]]]]],




       [[[[[0]],

          [[0]],

          [[0]]]],



        [[[[3]],

          [[0]],

          [[6]]]]]])

In [59]:
a3.reshape(4,2,1,3,1,1).ndim

6

In [60]:
# Now consde the example below

a3.reshape(4,-1)

# Here '-1' will represent default
# which is rest of the factor of 24
# and it will try to add that number in the shape
# in the above example it added 6
# so the array is now in shape of (4,6)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4],
       [0, 0, 0, 3, 0, 6]])

In [61]:
# We can also do it like this

a3.reshape(3,2,-1)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 1, 0, 2],
        [0, 0, 0, 2]],

       [[0, 4, 0, 0],
        [0, 3, 0, 6]]])

In [62]:
a3.reshape(3,2,-2365234)

# It works with anu '-' number
# Not necessarly only -1

array([[[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 1, 0, 2],
        [0, 0, 0, 2]],

       [[0, 4, 0, 0],
        [0, 3, 0, 6]]])

Range Function in numpy

In [64]:
# Traditionally we have a range function
# Which gibes a data set

list(range(4,10,2))

# So here we have set the 2 as the jump value

[4, 6, 8]

In [65]:
# But from the above we can't keep the 
# jump value as 0.2 
# because this range function will only take 
# integer as the jump values.

list(range(4,10,0.2))

# This is why the error

TypeError: 'float' object cannot be interpreted as an integer

In [66]:
# In numpy 
# We have 'arange' function 

np.arange(4,10,0.2)

# Here we are able to give the floting
# value as the jump value

array([4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4,
       6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. ,
       9.2, 9.4, 9.6, 9.8])

In [68]:
# It also works like this

np.arange(4,10.5,0.2)

# In the 'arange' function 
# we can pass flot values as well

array([ 4. ,  4.2,  4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,
        6.2,  6.4,  6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,
        8.4,  8.6,  8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4])

Data manupulation using numpy

In [70]:
# Here as we have seen the slicing works 
# same as normal list slicing operations

a5 = np.arange(4,10.5,0.2)

a5[1:4]

array([4.2, 4.4, 4.6])

In [72]:
arr = np.random.rand(4,5)
arr

array([[0.65990096, 0.91398494, 0.53357758, 0.96295561, 0.13420941],
       [0.52167701, 0.95400941, 0.751928  , 0.52738593, 0.51897101],
       [0.86108214, 0.34441831, 0.26518617, 0.00974838, 0.60578455],
       [0.22391485, 0.50928918, 0.15394794, 0.920348  , 0.02766666]])

In [75]:
# Requirement:
# to get all the values which are greater then 0.5

arr[arr > 0.5]

# Simillar to pandas slicing and Data manupulation

array([0.65990096, 0.91398494, 0.53357758, 0.96295561, 0.52167701,
       0.95400941, 0.751928  , 0.52738593, 0.51897101, 0.86108214,
       0.60578455, 0.50928918, 0.920348  ])

In [76]:
# Simillarly to Iloc and loc function
# We can extract the value. 

arr[[1,2],[2]]

# Same [1,2] are the rows indexes 
# and [2] is the column index

array([0.751928  , 0.26518617])

In [77]:
# TO use 'iloc' and 'loc' 
# we hae to convert it into a df

In [79]:
arr1 = np.random.rand(8,5)
arr1

array([[0.13655601, 0.49088335, 0.01055404, 0.62553327, 0.68778408],
       [0.67483288, 0.42133251, 0.12223886, 0.14402038, 0.22633544],
       [0.9740371 , 0.37632416, 0.15540196, 0.02788841, 0.41842265],
       [0.20627645, 0.07312893, 0.72797774, 0.81483298, 0.6641901 ],
       [0.90591137, 0.29128499, 0.95422658, 0.7163712 , 0.86248215],
       [0.46812456, 0.76356711, 0.4026388 , 0.59783839, 0.65808809],
       [0.49417301, 0.38351915, 0.00180407, 0.20338189, 0.9707932 ],
       [0.21266294, 0.87637106, 0.5117774 , 0.29377184, 0.18935126]])

In [88]:
# Requirement:
# to get data from row 2nd to last
# and column 1st to 3rd

arr2 = arr1[1:8, 0:3]
arr2
# Exactly same as 
# arr1[[1,2,3,4,5,6,7], [0,1,2]]

# Here you dn't have to incase the indexs into []
# because you are mentioning a range
# In case you are mentioning certain index values only
# then you have to pass it as a list

# NOTE: 
# Make sure to remenber that the last one will ne n+1

array([[0.67483288, 0.42133251, 0.12223886],
       [0.9740371 , 0.37632416, 0.15540196],
       [0.20627645, 0.07312893, 0.72797774],
       [0.90591137, 0.29128499, 0.95422658],
       [0.46812456, 0.76356711, 0.4026388 ],
       [0.49417301, 0.38351915, 0.00180407],
       [0.21266294, 0.87637106, 0.5117774 ]])

In [90]:
# If you want to change sertain value in that data
# Same as list manupulatiom

arr2[0][0]= 10
arr2

array([[1.00000000e+01, 4.21332506e-01, 1.22238861e-01],
       [9.74037096e-01, 3.76324164e-01, 1.55401963e-01],
       [2.06276446e-01, 7.31289339e-02, 7.27977743e-01],
       [9.05911373e-01, 2.91284988e-01, 9.54226580e-01],
       [4.68124557e-01, 7.63567107e-01, 4.02638800e-01],
       [4.94173007e-01, 3.83519152e-01, 1.80406893e-03],
       [2.12662938e-01, 8.76371065e-01, 5.11777402e-01]])

In [97]:
# We can also perform element vise multiplication 
# with array multiplications

m1 = np.array([[1,2], [3,4]])
m2 = np.array([[2,3], [4,5]])

In [98]:
m1

array([[1, 2],
       [3, 4]])

In [99]:
m2

array([[2, 3],
       [4, 5]])

In [100]:
# each element is multiplied with 
# the corresponding index element 
# form the other array

m1*m2

array([[ 2,  6],
       [12, 20]])

In [101]:
# In numpy we can perform mar multiplication
# By using "@" symbol instred of "*"

m1@m2

array([[10, 13],
       [22, 29]])

In [104]:
# And Matrix multiplication 
# We can convert the array into matrixes

m1 = np.matrix(m1)
m2 = np.matrix(m2)
m = m1*m2
m

# NOTE:

# Same rules apply here as well 
# What we have studied in schools
# That (column of mat1) = (row of mat2)

matrix([[10, 13],
        [22, 29]])

In [105]:
m/0

# Ideally this should give
# DivisibleByZero Error
# But in numpy the error does not come
# It gives 'infinity'

# "inf" is a keyword in numpy only nott in core Python

C:\Users\win\AppData\Local\Temp\ipykernel_20648\3791875896.py:1: RuntimeWarning: divide by zero encountered in divide
  m/0


matrix([[inf, inf],
        [inf, inf]])

Zeros and Ones Function

In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,54]

In [3]:
np.asarray(l)

array([ 1,  2,  3,  4, 54])

In [4]:
np.zeros(5)

# This will create a 1D array
# which will have 5 zero elemnts

array([0., 0., 0., 0., 0.])

In [5]:
np.zeros((3,4))

# This will create a 2D array 
# Of 3x4 row and columns

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.zeros((3,4,5))

# This will creat a 3D array
# with 3 2D arrays of 4x5 rows and columns

# As we keep increasing the elements
# inside the () the dimention  
# will increase accordingly

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [7]:
# Simillarly we have ones() function

np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [8]:
np.ones((3,6,4))

# Works exactly like the zeros() function 
# instred of zeros it will have 
# all elements has 1

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [9]:
# Now to convert these zeros and ones array
# Into another number array

5 + np.zeros((3,4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])